server {
    server_name astra.paycrm.space;

    client_max_body_size 50m;

    access_log /var/log/nginx/astra-prod.access.log;
    error_log /var/log/nginx/astra-prod.error.log;

    location /api/ {
        proxy_pass http://127.0.0.1:8081;
        include /etc/nginx/snippets/astra-proxy-headers.conf;
    }

    location / {
        proxy_pass http://127.0.0.1:3001;
        include /etc/nginx/snippets/astra-proxy-headers.conf;
    }

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/astra.paycrm.space/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/astra.paycrm.space/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = astra.paycrm.space) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    listen [::]:80;
    server_name astra.paycrm.space;
    return 404; # managed by Certbot


}