package audit

const (
	ActionUserCreated                       = "user.created"
	ActionUserUpdated                       = "user.updated"
	ActionUserPasswordReset                 = "user.password_reset"
	ActionRequisiteCreated                  = "requisite.created"
	ActionRequisiteUpdated                  = "requisite.updated"
	ActionRequisiteArchived                 = "requisite.archived"
	ActionRequisiteAssigned                 = "requisite.assigned"
	ActionRequisiteReassigned               = "requisite.reassigned"
	ActionRequisiteUnassigned               = "requisite.unassigned"
	ActionShiftCreated                      = "shift.created"
	ActionShiftRequisiteTaken               = "shift.requisite_taken"
	ActionShiftDailyDetailsUpdated          = "shift.daily_details_updated"
	ActionShiftTurnoverAdded                = "shift.turnover_added"
	ActionShiftRequisiteClosed              = "shift.requisite_closed"
	ActionShiftRequisiteCorrected           = "shift.requisite_corrected"
	ActionShiftRequisiteReturnedToWork      = "shift.requisite_returned_to_work"
	ActionShiftInternalTransferCreated      = "shift.internal_transfer_created"
	ActionShiftInternalTransferCancelled    = "shift.internal_transfer_cancelled"
	ActionManualPayoutCreated               = "manual_payout.created"
	ActionManualPayoutUpdated               = "manual_payout.updated"
	ActionManualPayoutCancelled             = "manual_payout.cancelled"
	ActionManualPayoutTransferAdded         = "manual_payout.transfer_added"
	ActionManualPayoutTransferUpdated       = "manual_payout.transfer_updated"
	ActionManualPayoutTransferDeleted       = "manual_payout.transfer_deleted"
	ActionImportApplied                     = "import.applied"
	ActionReconciliationCreated             = "reconciliation.created"
	ActionReconciliationConfirmed           = "reconciliation.confirmed"
	ActionReconciliationRejected            = "reconciliation.rejected"
	ActionReconciliationApplied             = "reconciliation.applied"
	ActionReconciliationAcceptedWithComment = "reconciliation.accepted_with_comment"
	ActionShiftClosed                       = "shift.closed"
)
